a = 5;
b = 6;
c = 3;
d = 2;
e = input('a number e = ');
f= input('a number f = ');
g = input('a number g = ');
i = input('a number i = ');
x = a+e;
y= a-f;
z= i/b;
t = c*g;
fprintf('%d + %d = %d \n',a,e,x);
fprintf('%d - %d = %d \n',a,f,y);
fprintf('%d / %d = %d \n',b,i,z);
fprintf('%d * %d = %d \n',c,g,t);